name: Archiv
description: Eine App, die verschiedene Projekte vorstellt.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
    
  provider: ^6.0.0
  supabase_flutter: ^1.6.2
  url_launcher: ^6.2.1
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  http: ^1.1.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path: "assets/icon.png" 
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  remove_alpha_ios: true

flutter:
  uses-material-design: true